// packages/plugin-packages/mashroom-portal-demo-svelte-app/src/App.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import logo from './assets/svelte-logo.svg';

  export let messageBus: any;
  export let appConfig: { firstName?: string, pingButtonLabel?: string } = {};
  let pings = 0;

  const incrementPing = (): number => pings += 1;

  messageBus.subscribe('ping', incrementPing);

  const sendPing = (): void => messageBus.publish('ping', {});

  onDestroy(() => {
      messageBus.unsubscribe('ping', incrementPing);
  });
</script>

<style>
    .example-svelte-app {
        padding: 10px;
        display: flex;
    }

    .svelte-logo {
        margin-left: 30px;
        margin-right: 20px;
        height: 80px;
        width: 60px;
        align-self: center;
    }

    button {
        margin-right: 10px;
    }
</style>

<div class='example-svelte-app'>
    <div class="svelte-logo">
        {@html logo}
    </div>
    <div class="demo-svelte-app-content">
        <h4>Svelte Demo App</h4>
        <p>Hello {appConfig.firstName}!</p>
        <div>
            <button on:click={sendPing}>
                {appConfig.pingButtonLabel || 'Send Ping'}
            </button>
            <span>Received pings: {pings}</span>
        </div>
    </div>
</div>

// packages/plugin-packages/mashroom-portal-demo-vue-app/src/js/App.vue
<template>
    <div class="mashroom-demo-vue-app">
        <img :src="resourcesBasePath + '/assets/vue_logo.png'" width="76" height="76" alt="Vue" />
        <div class="demo-vue-app-content">
            <h4>Vue Demo App</h4>
            <p>Hello {{firstName}}!</p>
            <div>
                <button v-on:click="onClick">
                    {{pingButtonLabel || 'Send Ping'}}
                </button>
                <span>Received pings: {{pings}}</span>
            </div>
        </div>
    </div>
</template>

<script>
    let processPing = null;

    export default {
        name: 'app',
        props: ['resourcesBasePath', 'firstName', 'pingButtonLabel', 'messageBus'],
        data: () => ({
            pings: 0
        }),
        mounted: function() {
            processPing = () => this.pings ++;
            this.messageBus.subscribe('ping', processPing);
        },
        beforeDestroy: function() {
            this.messageBus.unsubscribe('ping', processPing);
        },
        methods: {
            onClick() {
                this.messageBus.publish('ping', {});
            }
        },
        components: {
        },
    };
</script>

<style>
    .mashroom-demo-vue-app {
        padding: 10px;
        display: flex;
        align-items: center;
    }

    .mashroom-demo-vue-app img {
        height: 76px;
        margin: 0 20px;
    }

    .mashroom-demo-vue-app button {
        margin-right: 10px;
    }
</style>
