// packages/plugin-packages/mashroom-portal-demo-angular-app/src/app/app.component.ts
import {ChangeDetectorRef, Component, Inject} from '@angular/core';

import {MashroomPortalAppSetup, MashroomPortalClientServices, MashroomPortalMessageBus} from '@mashroom/mashroom-portal/type-definitions';

@Component({
    selector: 'angular-demo-app',
    templateUrl: './app.component.html',
    providers: []
})
export class AppComponent {

    firstName: string;
    resourcesBasePath: string;
    pings: number;
    messageBus: MashroomPortalMessageBus;

    constructor(cdRef: ChangeDetectorRef, @Inject('app.setup') private appSetup: MashroomPortalAppSetup, @Inject('client.services') private clientServices: MashroomPortalClientServices) {
        this.resourcesBasePath = appSetup.resourcesBasePath;
        this.firstName = appSetup.appConfig.firstName;
        this.pings = 0;
        this.messageBus = clientServices.messageBus;
        this.messageBus.subscribe('ping', () => {
            this.pings++;
            cdRef.detectChanges();
        });
    }

    sendPing() {
        this.messageBus.publish('ping', {});
    }
}

<div class="mashroom-demo-angular-app">
    <img src="{{resourcesBasePath}}/assets/Angular_logo.svg" width="80" height="80" alt="Angular" />
    <div class="demo-angular-app-content">
        <h4>Angular Demo App</h4>
        <p>Hello {{firstName}}!</p>
        <div>
            <button (click)="sendPing()">
                {{pingButtonLabel || 'Send Ping'}}
            </button>
            <span>Received pings: {{pings}}</span>
        </div>
    </div>
</div>

// packages/plugin-packages/mashroom-portal-demo-react-app/src/js/App.tsx

import React, {PureComponent} from 'react';
import InlineSVG from './InlineSVG';
import ReactLogo from '../assets/React-icon.svg';

import type {MashroomPortalMessageBus} from '@mashroom/mashroom-portal/type-definitions';

type Props = {
    appConfig: {
        firstName?: string;
        pingButtonLabel?: string;
    };
    messageBus: MashroomPortalMessageBus;
}

type State = {
    pings: number;
}

export default class App extends PureComponent<Props, State> {

    pingReceiver: () => void;

    constructor(props: Props) {
        super(props);
        this.state = {
            pings: 0,
        };
        this.pingReceiver = () => {
            this.setState({
                pings: this.state.pings + 1,
            });
        };
    }

    componentDidMount() {
        this.props.messageBus.subscribe('ping', this.pingReceiver);
    }

    componentWillUnmount() {
        this.props.messageBus.unsubscribe('ping', this.pingReceiver);
    }

    sendPing() {
        this.props.messageBus.publish('ping', {});
    }

    render() {
        return (
            <div className='mashroom-demo-react-app'>
                <InlineSVG className='react-logo' svgData={ReactLogo}/>
                <div className="demo-react-app-content">
                    <h4>React Demo App</h4>
                    <p>Hello {this.props.appConfig.firstName}!</p>
                    <div>
                        <button onClick={this.sendPing.bind(this)}>
                            {this.props.appConfig.pingButtonLabel || 'Send Ping'}
                        </button>
                        <span>Received pings: {this.state.pings}</span>
                    </div>
                </div>
            </div>
        );
    }

}
