// packages/plugin-packages/mashroom-portal-demo-solidjs-app/src/js/App.tsx

import { onMount, onCleanup, createSignal } from 'solid-js';
import logo from '../assets/solidjs.svg';
import type {MashroomPortalMessageBus} from '@mashroom/mashroom-portal/type-definitions';

type Props = {
    appConfig: {
        message?: string;
        pingButtonLabel?: string;
    };
    messageBus: MashroomPortalMessageBus;
}

export default ({appConfig: {message, pingButtonLabel}, messageBus}: Props) => {
    const [pings, setPings] = createSignal(0);
    const pingReceiver = () => {
        setPings(pings() + 1);
    };
    onMount(() => {
        messageBus.subscribe('ping', pingReceiver);
    });
    onCleanup(() => {
        messageBus.unsubscribe('ping', pingReceiver);
    });
    const sendPing = () => {
        messageBus.publish('ping', {});
    };
    return (
        <div class='mashroom-demo-solidjs-app'>
            <div class='demo-solidjs-app-logo' innerHTML={logo} />
            <div class="demo-solidjs-app-content">
                <h4>SolidJS Demo App</h4>
                <p>{message}</p>
                <div>
                    <button onClick={sendPing}>
                        {pingButtonLabel || 'Send Ping'}
                    </button>
                    <span>Received pings: {pings()}</span>
                </div>
            </div>
        </div>
    );
};

// packages/plugin-packages/mashroom-portal-demo-isomorphic-react-app/src/frontend/js/App.jsx
// @flow

import React, {PureComponent} from 'react';
import ReactLogo from '../assets/React-icon.svg';

import type {MashroomPortalMessageBus} from '@mashroom/mashroom-portal/type-definitions';

type Props = {
    appConfig: {
        firstName: string
    },
    messageBus: MashroomPortalMessageBus
}

type State = {
    pings: number
}

export default class App extends PureComponent<Props, State> {

    pingReceiver: () => void;

    constructor() {
        super();
        this.state = {
            pings: 0,
        };
        this.pingReceiver = () => {
            this.setState({
                pings: this.state.pings + 1,
            });
        };
    }

    componentDidMount() {
        this.props.messageBus.subscribe('ping', this.pingReceiver);
    }

    componentWillUnmount() {
        this.props.messageBus.unsubscribe('ping', this.pingReceiver);
    }

    sendPing() {
        this.props.messageBus.publish('ping', {});
    }

    render() {
        return (
            <div className='mashroom-demo-react-app'>
                <div className='react-logo'>
                    <ReactLogo />
                </div>
                <div className="demo-react-app-content">
                    <h4>React Demo App</h4>
                    <p>Hello {this.props.appConfig.firstName}!</p>
                    <div>
                        <button onClick={this.sendPing.bind(this)}>Send Ping</button>
                        <span>Received pings: {this.state.pings}</span>
                    </div>
                </div>
            </div>
        );
    }

}
