// packages/plugin-packages/mashroom-portal-demo-isomorphic-react-app/src/frontend/js/index.js
// @flow

import '../sass/style.scss';

import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

import type {MashroomPortalAppPluginBootstrapFunction} from '@mashroom/mashroom-portal/type-definitions';

const bootstrap: MashroomPortalAppPluginBootstrapFunction = (portalAppHostElement, portalAppSetup, clientServices) => {
    ReactDOM.hydrate(<App appConfig={portalAppSetup.appConfig} messageBus={clientServices.messageBus}/>, portalAppHostElement);

    return Promise.resolve({
        willBeRemoved: () => {
            console.info('Ummounting React app');
            ReactDOM.unmountComponentAtNode(portalAppHostElement)
        }
    });
};

global.startIsomorphicReactDemoApp = bootstrap;

// packages/plugin-packages/mashroom-portal-demo-solidjs-app/src/js/index.tsx
import '../sass/style.scss';

import {render} from 'solid-js/web';
import App from './App';

import type {MashroomPortalAppPluginBootstrapFunction} from '@mashroom/mashroom-portal/type-definitions';

const bootstrap: MashroomPortalAppPluginBootstrapFunction = (portalAppHostElement, portalAppSetup, clientServices) => {
    const {appConfig, user} = portalAppSetup;
    const {messageBus} = clientServices;

    // Solid does not remove all existing children
    portalAppHostElement.innerHTML = '';

    const dispose = render(() => (
        <App appConfig={appConfig} messageBus={messageBus}/>
    ), portalAppHostElement);

    return {
        willBeRemoved: () => {
            console.info('Unmounting SolidJS App');
            dispose();
        }
    };
};

(global as any).startSolidJSDemoApp = bootstrap;
